version: '3.8'
services:
  framework:
    # build: ./opse-framework/core
    build: ./core
    hostname: framework.opse
    ports:
      - "6060:6060"
    container_name: opse-framework
    networks:
      opse_net:
        ipv4_address: 10.10.150.20

  gui:
    # build: ./opse-gui
    build: ../opse-gui
    hostname: gui.opse
    ports:
      - "8080:80"
    container_name: opse-gui
    networks:
      opse_net:
        ipv4_address: 10.10.150.10

networks:
  opse_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.150.0/24